run_name: 'vae'
model:
  latent_dim: 2
  conv1:
    channels: 4
    kernel_size: 3
    stride: 2
    padding: 1
    output_padding: 1
  conv2:
    channels: 8
    kernel_size: 3
    stride: 2
    padding: 1
    output_padding: 1
training:
  seed: 42
  beta: 0.1
  epochs: 100
  batch_size: 64
  lr: 0.001
  momentum: 0.9
    
